# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o timefiller-win64
      
    - name: Build Mac
      run: GOOS=darwin GOARCH=arm64 go build -o timefiller-darwinm1
      
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "timefiller-*"
        body: "TEST"
        name: $(git rev-parse --short "$GITHUB_SHA")
